### ISSUE TITLE
Use new autogenerating password capability of provider-aws in Database abstraction

### ISSUE THREAD

**Issue by ytsarev** [upbound/platform-ref-aws#101]
### What problem are you facing?

Currently, we have to create manually crafted [password secrets](https://github.com/upbound/platform-ref-aws/blob/main/examples/mariadb-claim.yaml#L18-L26) for Database claims 

### How could Upbound help solve your problem?

We can use https://marketplace.upbound.io/providers/upbound/provider-aws/v0.32.1/resources/rds.aws.upbound.io/Instance/v1beta1#doc:spec-forProvider-autoGeneratePassword and deprecate manually created password

**Comment by haarchri** [comment]
@ytsarev  @jbw976  please checkout https://github.com/upbound/platform-ref-aws/pull/111 add an option for `autoGeneratePassword`
