### ISSUE TITLE
XServices should only contain 1 helm release

### ISSUE THREAD

**Issue by stevendborrelli** [upbound/platform-ref-aws#114]
### What problem are you facing?

Currently XServices installs both a Prometheus and Universal-Crossplane chart. 

### How could Upbound help solve your problem?

- Update `XServices` to only deploy 1 generic Helm release
- Update API for helm parameters
- Split out provisioning of each chart into a separate XR.

Epic #

**Comment by ytsarev** [comment]
What's wrong with multiple Releases? `XServices` semantically matching multiple services to install

**Comment by haarchri** [comment]
With functions, we can create a versatile input fields for Helm releases, allowing users to add as many releases as they need. 

Additionally, we open the door to deploying GitOps systems like Flux, which enables users to install additional required Helm charts through GitOps. https://github.com/upbound/platform-ref-aws/pull/116

**Comment by ytsarev** [comment]
In addition to the above, I tend to deprecate `XServices` and provide a separate dedicated abstraction per Service like `Prometheus` , `Flux` or `ArgoCD` as separate optional configurations to install
