### ISSUE TITLE
Deploy Argo as part of the platform

### ISSUE THREAD

**Issue by jbw976** [upbound/platform-ref-aws#22]
This would allow us to show CI/CD integration as well:  bring up the platform, show the console, show the Argo UI

Argo could then help manage deployment of apps into the platform too.

"aws ref platform with full GitOps support for app + infra" - @prasek

**Comment by jbw976** [comment]
Another option here could be Flux as that it what is being evangelized by AWS in their paris distro.

**Comment by jbw976** [comment]
We could consider doing this in a separate dedicated reference platform, instead of only as part of platform-ref-aws.

**Comment by natereid72** [comment]
This is sort of.a flipside approach from what Viktor did that I took with CP and ArgoCD. It's a shell script that installs argo cd in a cluster, that then installs uxp, a config pkg equivalent, a sample XR/XRC. and Gatekeeper.

**Comment by jbw976** [comment]
I think deploying Argo/Flux or GitOps is better served in a specific reference platform for that.  For example https://marketplace.upbound.io/configurations/devops-toolkit/dot-gitops/, or other GitOps focused reference platform that may be created in the future 😊
