### ISSUE TITLE
Should the `CompositeNetwork` XRD offer a claim?

### ISSUE THREAD

**Issue by negz** [upbound/platform-ref-aws#25]
```console
$ kubectl get xrd
NAME                                                         ESTABLISHED   OFFERED   AGE
compositeclusters.aws.platformref.crossplane.io              True          True      28m
compositenetworks.aws.platformref.crossplane.io              True          True      28m
compositepostgresqlinstances.aws.platformref.crossplane.io   True          True      28m
eks.aws.platformref.crossplane.io                            True                    28m
services.aws.platformref.crossplane.io                       True                    28m
```

VPC networks are typically the canonical example of the kind of infrastructure platform operators want to manage, but platform consumers probably don't want to manage. Do we really want consumers managing VPC networks?

**Comment by grantgumina** [comment]
@negz @jbw976 - this is actually why I was thinking to have the operator create the network in the cluster scope view. The resources provisioned from the user consoles can still interact with these objects, but the consumers don't see them. 

Thoughts?

**Comment by jbw976** [comment]
After @natereid72 initial efforts in https://github.com/upbound/platform-ref-azure/pull/1, I'm seeing potential to go ahead and remove the Network claim for all of our reference platforms.  Some thoughts from Slack:

i wonder if the model should be:
1. user creates a cluster and provides some sort of identifier for it
1. all of the underlying infrastructure (e.g. networking and resource group) come along for the ride inside the cluster composition and use this single ID (with transforms as needed)
1. user creates a database and specifies the cluster ID to connect the database and the cluster

this results in only 1 ID field needing to be set i believe in all 3 cloud scenarios, it streamlines the experience, and removes the environment details of networking from the users concern. this could be an improvement, but we’d need to think through it a bit more.

**Comment by jbw976** [comment]
@garreeoke this PR from @natereid72 is a great example of the work that needs to be implemented for this issue: https://github.com/upbound/platform-ref-azure/pull/3

Let us know if there are any questions and we're always happy to sit down and do a sync pairing session together to make progress!
