### ISSUE TITLE
connection secret namespaces should not be hard coded

### ISSUE THREAD

**Issue by jbw976** [upbound/platform-ref-aws#36]
We hard code the namespace where we expect a secret to exist in this reference platform, for example:

https://github.com/upbound/platform-ref-aws/blob/master/cluster/eks/composition.yaml#L177

We should be taking the namespace in as an input, by using the same value as is on the XR, like we do in some other places:

https://github.com/upbound/platform-ref-aws/blob/master/cluster/eks/composition.yaml#L71-L72

**Comment by stevendborrelli** [comment]
With the release of `up` installing uxp into Upbound-system namespace, this is causing issues in some test environments.

**Comment by jbw976** [comment]
Actually this should have been fixed/closed in #42 and #44 - we're still seeing this in v0.1.3 @stevendborrelli? Can you add more info/debugging information so we can determine if this is a new issue or if this wasn't fixed completely? Thank you!

**Comment by haarchri** [comment]
we writing only connections secrets to `upbound-system` after https://github.com/upbound/platform-ref-aws/pull/116 and in claim namespace if configured
