### ISSUE TITLE
Standardize namespaces in Upbound Cloud reference packages

### ISSUE THREAD

**Issue by grantgumina** [upbound/platform-ref-aws#52]
If you install the public reference packages for AWS into an UXP hosted cluster using the UI, they are installed into the Crossplane-system namespace. Is this the expected behavior or should they be installed into upbound-system.

```
kubectl get all -n crossplane-system 
NAME                                                     READY   STATUS    RESTARTS   AGE
crossplane-provider-aws-3b7ef8509173-5579ccb577-bms8m    1/1     Running   0          47m
crossplane-provider-helm-accc448deaad-7d9b478bf7-48w4j   1/1     Running   0          47m
```

**Comment by hasheddan** [comment]
@grantgumina the namespace that provider controllers are installed into is not controlled by the packages. It is relative to the namespace that Crossplane itself is installed into.

**Comment by grantgumina** [comment]
@hasheddan understood. What I'm saying though is that since these reference platform repositories lives in the Upbound organization on GitHub, we should make sure the documentation assumes UXP usage. :)

**Comment by grantgumina** [comment]
@stevendborrelli agreed to tackle this during this sprint

**Comment by stevendborrelli** [comment]
Closing this issue, all the secret refs are in `upbound-system`
