### ISSUE TITLE
Release platform-ref-aws:v0.3.0 

### ISSUE THREAD

**Issue by jbw976** [upbound/platform-ref-aws#67]
There's been a few recent PRs that we should include in an official release for v0.3.0, e.g. #63 and #65.

Any volunteers to run the release? Happy to pair with you :)

**Comment by Piotr1215** [comment]
This sounds exciting :). I'll be happy to pair with you @jbw976 and run the release.

**Comment by stevendborrelli** [comment]
We should get out a release ASAP, as the changes to the CRDs from #65 cause the installation of the example cluster to fail if installing the v0.2.2 package:

**Comment by stevendborrelli** [comment]
@Piotr1215 @jbw976 let me know if you would like to collaborate on this. I have a PR to update the version, we can go through the release process.

**Comment by Piotr1215** [comment]
@stevendborrelli apologies for the late reply, I'd be happy to collaborate on the release.
