### ISSUE TITLE
Docs: Enhance the quick start guide with a declarative approach 

### ISSUE THREAD

**Issue by luebken** [upbound/platform-ref-aws#80]
### What problem are you facing?

The current quick start uses imperative commands from `up` to make it concise and hopefully easy to understand. This setup is not for production use-cases. There and in any GitOps powered workflows users should use a dedeclarative approach

### How could Upbound help solve your problem?

Enhance the guide or write a new guide that shows the declarative style including all the options a user has.

**Comment by haarchri** [comment]
In the Crossplane ecosystem, we currently utilize a marketplace for all configurations. This setup allows interested users to seamlessly install any configuration by simply clicking the 'Install' button, offering a declarative approach. https://marketplace.upbound.io/configurations/upbound/platform-ref-aws/
