### ISSUE TITLE
Create composition with IAM roles for service accounts

### ISSUE THREAD

**Issue by jeanduplessis** [upbound/platform-ref-aws#85]
### What problem are you facing?
Many users have a need to configure IAM roles for service accounts (IRSA) for services. 
This doesn't seem possible to fully automate with providers.

Related conversation: https://github.com/crossplane-contrib/provider-aws/issues/796

### How could Upbound help solve your problem?

Look into creating a composition similar to `platform-ref-aws` that creates an EKS cluster that already has the IRSA setup automatically figured out without using `eksctl`. 

Relates to private issue: https://github.com/upbound/official-providers/issues/829

**Comment by ytsarev** [comment]
@jeanduplessis we already have `OpenIDConnectProvider` in this platform https://github.com/upbound/platform-ref-aws/blob/ea3579c/package/cluster/eks/composition.yaml#L190-L192

Is anything else required?

**Comment by jeanduplessis** [comment]
Thanks @ytsarev for confirming. Closing this issue.

**Comment by jbw976** [comment]
@ytsarev that one little `OpenIDConnectProvider` replaces all the eksctl etc. craziness in https://github.com/crossplane-contrib/provider-aws/blob/master/AUTHENTICATION.md#using-iam-roles-for-serviceaccounts? 🤔 🤯

**Comment by ytsarev** [comment]
@jbw976 hm, I probably misunderstood the scope originally. So we need to create IRSA Composition to enable provider Authentication with IRSA? Which seems interesting chicken-egg,

I will reopen it for discussion.
